### ISSUE TITLE
RPi.GPIO module not installing

### ISSUE THREAD

**Issue by sidhu1310** [CodersCafeCommunity/AutoBill#1]
![Screenshot (10)](https://github.com/CodersCafeTech/AutoBill/assets/145716211/0268779e-bf49-49fb-88e7-d20d83c48ab5)

**Comment by ShebinJoseJacob** [comment]
Could you please let me know why you're trying to install RPI.GPIO on Windows? It is supposed to be installed on Raspberry Pi, not on Windows PC.

**Comment by sidhu1310** [comment]
Thank  you i didn't knew that before
